name: mycarparkingapp
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  objectbox: ^4.0.3
  json_annotation: ^4.6.0
  http: ^1.2.2
  shelf: ^1.3.0
  shelf_router: ^1.1.0
 

 
  
  

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  build_runner: ^2.4.13
  objectbox_generator: ^4.0.3

